import {
  Box,
  Button,
  Card,
  CardBody,
  Container,
  HStack,
  Heading,
  SimpleGrid,
  Stack,
  Text,
  VStack,
} from "@chakra-ui/react";
import { GetStaticProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import Image from "next/image";
import { Foods, Trending } from "~/@types";

import Cake from "~/assets/icons/Cake.svg";
import Doughnut from "~/assets/icons/Doughnut.svg";
import Kebab from "~/assets/icons/Kebab.svg";
import Pizza from "~/assets/icons/Pizza.svg";
import Salmon from "~/assets/icons/Salmon.svg";
import Hero from "~/assets/images/Hero.png";
import bgHero from "~/assets/images/bgHoverReceipt.png";
import DonerKebab from "~/assets/images/burito.png";
import CupCake from "~/assets/images/chocolateCake.png";
import DoughnutMilk from "~/assets/images/doughnut.png";
import DoughnutUnicorn from "~/assets/images/doughnutWithUnicorn.png";
import FullPizza from "~/assets/images/pizza.png";
import KathiKebab from "~/assets/images/satai.png";
import SlicePizza from "~/assets/images/slicePizza.png";
import SalmonRoll from "~/assets/images/sushi.png";
import { BottomBar, Footer, Navbar } from "~/components";
import { Caraousel } from "~/features/caraousel";

export default function Home({
  category,
  trending,
}: InferGetServerSidePropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Test Elemes Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        maxW="1440px"
        px={{
          base: "32px",
          md: "116px",
        }}
      >
        <Navbar />
        <Stack
          direction={{
            base: "column",
            md: "row",
          }}
          justifyContent="space-between"
          spacing={10}
          mt="45px"
          _before={{
            content: "''",
            backgroundImage: bgHero.src,
            backgroundSize: "full",
            rounded: "full",
            backgroundRepeat: "no-repeat",
            position: "absolute",
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
            opacity: 0.05,
          }}
          position="relative"
        >
          <VStack align="start" spacing={0}>
            <Heading
              fontSize="48px"
              lineHeight="64px"
              color="primary.500"
              fontWeight="medium"
            >
              Good Food Us
            </Heading>
            <Heading fontSize="48px" color="primary.500" fontWeight="medium">
              Good Mood
            </Heading>
            <VStack
              align="start"
              mt="32px"
              display={{
                base: "none",
                md: "flex",
              }}
              spacing="19px"
            >
              <Text fontSize="18px" lineHeight="29px" color="#757575" w="482px">
                I would think that conserving our natural resources should be a
                conservative position: Not to waste food, and not to throw away
                a lot of the food that we buy.
              </Text>
              <HStack>
                <Button
                  w="147px"
                  h="42px"
                  rounded="100px"
                  px="10px"
                  py="18px"
                  fontSize="14px"
                  fontWeight="medium"
                  lineHeight="22px"
                  color="white"
                  colorScheme="primary"
                  shadow="0px 8px 32px 0px rgba(102, 107, 226, 0.35)"
                >
                  Daftar Sekarang
                </Button>
                <Button
                  w="98px"
                  h="42px"
                  rounded="100px"
                  fontSize="14px"
                  fontWeight="medium"
                  lineHeight="22px"
                  color="#333333"
                  bgColor="#F2F2F2"
                  _hover={{
                    bgColor: "#F2F2F2",
                  }}
                >
                  About Us
                </Button>
              </HStack>
            </VStack>
          </VStack>
          <Box
            w={{
              base: "230.85px",
              md: "480px",
            }}
            h={{
              base: "255.51px",
              md: "530.88px",
            }}
            rounded="full"
            display="flex"
            justifyContent="center"
            alignItems="center"
            bg="rgba(196, 196, 196, 0.2)"
            position="relative"
            _before={{
              content: "''",
              backgroundImage: bgHero.src,
              backgroundSize: "500px 250px",
              rounded: "full",
              backgroundRepeat: "no-repeat",
              position: "absolute",
              top: 0,
              right: 0,
              bottom: 0,
              zIndex: 999,
              left: 0,
              opacity: 0.05,
            }}
          >
            <Image
              src={Hero.src}
              width={Hero.width}
              style={{
                zIndex: 1,
                maxWidth: 412,
                maxHeight: 414,
                position: "relative",
              }}
              sizes="100vw"
              height={Hero.height}
              alt="Hero"
            />
            <Card
              position="absolute"
              w="292px"
              bottom={{
                base: -2,
                md: 5,
              }}
              right={{
                base: "-10.2rem",
                md: "16.8rem",
              }}
              zIndex="modal"
              h="93px"
              rounded="17px"
              bg="rgba(255, 255, 255, 0.74)"
              dropShadow="0 11px 39px 0 rgba(0, 0, 0, 0.07)"
            >
              <CardBody pt="18px" px="23px" pb="22px">
                <HStack>
                  <Image
                    src={Hero.src}
                    width={53}
                    height={53}
                    style={{
                      objectFit: "cover",
                    }}
                    alt="hero"
                  />
                  <VStack align="start" spacing="4px">
                    <Text
                      fontSize="14px"
                      fontWeight="semibold"
                      color="black"
                      lineHeight="22px"
                    >
                      Green Salad Tomato
                    </Text>
                    <Text fontSize="12px" lineHeight="14px" color="#757575">
                      Tomato
                    </Text>
                  </VStack>
                </HStack>
              </CardBody>
            </Card>
          </Box>
          <VStack
            align="start"
            mt={10}
            display={{
              base: "flex",
              md: "none",
            }}
            spacing="19px"
          >
            <Text fontSize="18px" lineHeight="29px" color="#757575">
              I would think that conserving our natural resources should be a
              conservative position: Not to waste food, and not to throw away a
              lot of the food that we buy.
            </Text>
            <HStack>
              <Button
                w="147px"
                h="42px"
                rounded="100px"
                px="10px"
                py="18px"
                fontSize="14px"
                fontWeight="medium"
                lineHeight="22px"
                color="white"
                colorScheme="primary"
                shadow="0px 8px 32px 0px rgba(102, 107, 226, 0.35)"
              >
                Daftar Sekarang
              </Button>
              <Button
                w="98px"
                h="42px"
                rounded="100px"
                fontSize="14px"
                fontWeight="medium"
                lineHeight="22px"
                color="#333333"
                bgColor="#F2F2F2"
                _hover={{
                  bgColor: "#F2F2F2",
                }}
              >
                About Us
              </Button>
            </HStack>
          </VStack>
        </Stack>
        <Heading
          fontWeight="medium"
          color="rgba(51, 51, 51, 1)"
          fontSize="24px"
          mt="120px"
          lineHeight="30px"
        >
          Browser Our Category
        </Heading>
        <Text color="primary.500" fontSize="24px" lineHeight="30px">
          Receipt
        </Text>
        <Box mt={10}>
          <Caraousel foods={category} />
        </Box>
        <Heading
          fontWeight="medium"
          mt="80px"
          color="rgba(51, 51, 51, 1)"
          fontSize="24px"
          lineHeight="30px"
        >
          Browser Our Trending
        </Heading>
        <Text color="primary.500" fontSize="24px" lineHeight="30px">
          Receipt
        </Text>
        <SimpleGrid
          columns={{
            base: 1,
            md: 4,
          }}
          mt="48px"
          mb={{
            base: "117px",
            md: "0",
          }}
          spacingX="20px"
          spacingY="30px"
        >
          {trending.map((el, idx) => (
            <VStack
              key={idx}
              w={{
                base: "402px",
                md: "100%",
              }}
              align="start"
              p="25px"
              cursor="pointer"
              dropShadow="0 11px 39px 0 rgba(0, 0, 0, 0.07)"
              spacing="18.1px"
              position="relative"
              _hover={{
                _before: {
                  content: "''",
                  backgroundImage: bgHero.src,
                  backgroundSize: {
                    base: "400px 300px",
                    md: "280px 300px",
                  },
                  objectFit: "contain",
                  backgroundPosition: "center",
                  backgroundRepeat: "no-repeat",
                  position: "absolute",
                  top: 0,
                  right: 0,
                  bottom: 0,
                  left: 0,
                  opacity: 0.2,
                },
              }}
              h={{
                base: "292px",
                md: "306px",
              }}
              rounded="17px"
              bg={el.backgroundColor}
            >
              <Image
                src={el.image}
                width={118.15}
                style={{
                  position: "relative",
                  zIndex: 1,
                }}
                height={114.31}
                alt={el.title}
              />
              <VStack align="start" spacing={0}>
                <Heading
                  whiteSpace="pre"
                  fontWeight="medium"
                  fontSize={{
                    lg: "24px",
                    "2xl": "26px",
                  }}
                  lineHeight="50px"
                >
                  {el.title}
                </Heading>
                <Text
                  fontSize="18px"
                  whiteSpace="nowrap"
                  lineHeight="21.33px"
                  color="primary.500"
                  fontWeight="medium"
                >
                  {el.label}
                </Text>
              </VStack>
              <HStack spacing="3.94px">
                {Array.from({ length: 5 }, (_, idx) =>
                  idx + 1 <= el.raiting ? (
                    <svg
                      width="11"
                      height="11"
                      key={idx}
                      viewBox="0 0 11 11"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <g clipPath="url(#clip0_313_425)">
                        <path
                          d="M10.9489 4.47381C10.868 4.23298 10.6264 4.06746 10.2861 4.01963L7.58706 3.64013L6.38004 1.27385C6.22781 0.975464 5.99045 0.804321 5.72877 0.804321C5.46709 0.804321 5.22972 0.975464 5.07752 1.27385L3.87053 3.64011L1.17149 4.01961C0.831123 4.06744 0.589553 4.23298 0.508675 4.47377C0.427817 4.71458 0.522698 4.98587 0.768942 5.21812L2.72198 7.05999L2.26092 9.66087C2.20029 10.003 2.30325 10.2076 2.40033 10.3189C2.51387 10.4492 2.6795 10.521 2.86672 10.521C3.00826 10.521 3.15901 10.4808 3.31467 10.4016L5.72877 9.17364L8.14286 10.4016C8.29857 10.4808 8.4493 10.521 8.59086 10.521H8.5909C8.77814 10.521 8.94377 10.4492 9.05731 10.3189C9.15436 10.2076 9.25734 10.003 9.1967 9.66083L8.73558 7.06001L10.6886 5.21816C10.9349 4.98591 11.0297 4.7146 10.9489 4.47381Z"
                          fill="#FF8412"
                        />
                      </g>
                      <defs>
                        <clipPath id="clip0_313_425">
                          <rect
                            width="10.4966"
                            height="10.1557"
                            fill="white"
                            transform="translate(0.480469 0.584961)"
                          />
                        </clipPath>
                      </defs>
                    </svg>
                  ) : (
                    <svg
                      width="11"
                      height="11"
                      key={idx}
                      viewBox="0 0 11 11"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <g clipPath="url(#clip0_313_429)">
                        <path
                          d="M10.8146 4.47381C10.7337 4.23298 10.4921 4.06745 10.1518 4.01963L7.45279 3.64013L6.24576 1.27385C6.09354 0.975464 5.85617 0.804321 5.59449 0.804321C5.33281 0.804321 5.09544 0.975464 4.94324 1.27385L3.73625 3.64011L1.03721 4.01961C0.696845 4.06744 0.455276 4.23298 0.374398 4.47377C0.29354 4.71458 0.388421 4.98587 0.634664 5.21812L2.5877 7.05999L2.12664 9.66087C2.06602 10.003 2.16898 10.2076 2.26605 10.3189C2.37959 10.4492 2.54522 10.521 2.73244 10.521C2.87398 10.521 3.02473 10.4808 3.1804 10.4016L5.59449 9.17364L8.00858 10.4016C8.16429 10.4808 8.31502 10.521 8.45658 10.521H8.45662C8.64386 10.521 8.80949 10.4492 8.92303 10.3189C9.02009 10.2076 9.12306 10.003 9.06242 9.66083L8.6013 7.06001L10.5543 5.21816C10.8006 4.98591 10.8955 4.7146 10.8146 4.47381V4.47381Z"
                          fill="#C9C9C9"
                        />
                      </g>
                      <defs>
                        <clipPath id="clip0_313_429">
                          <rect
                            width="10.4966"
                            height="10.1557"
                            fill="white"
                            transform="translate(0.346191 0.584961)"
                          />
                        </clipPath>
                      </defs>
                    </svg>
                  )
                )}
              </HStack>
            </VStack>
          ))}
        </SimpleGrid>
        <HStack justify="center" mt="68px">
          <Button
            colorScheme="primary"
            w="160px"
            h="50px"
            rounded="100px"
            display={{
              base: "none",
              md: "block",
            }}
            mb="250px"
          >
            ALL Receipt
          </Button>
        </HStack>
        <BottomBar />
        <Footer />
      </Container>
    </>
  );
}

export const getStaticProps: GetStaticProps<{
  category: Foods[];
  trending: Trending[];
}> = async (ctx) => {
  const category = [
    {
      image: Cake.src,
      label: "Cupcake",
      count: 22,
    },
    {
      image: Pizza.src,
      label: "Pizza",
      count: 25,
    },
    {
      image: Kebab.src,
      label: "Kebab",
      count: 12,
    },
    {
      image: Salmon.src,
      label: "Salmon",
      count: 22,
    },
    {
      image: Doughnut.src,
      label: "Doughnut",
      count: 11,
    },
    {
      image: Cake.src,
      label: "Cupcake",
      count: 22,
    },
  ];

  const trending: Trending[] = [
    {
      image: SlicePizza.src,
      title: "Pizza Paperoni",
      label: "Pizza",
      raiting: 5,
      backgroundColor: "secondary.bostonBlue.300",
    },
    {
      image: FullPizza.src,
      title: "Pizza Meat",
      label: "Pizza",
      raiting: 3,
      backgroundColor: "secondary.bostonBlue.300",
    },
    {
      image: DonerKebab.src,
      title: "Doner Kebab",
      label: "Kebab",
      raiting: 5,
      backgroundColor: "secondary.sanMarino.300",
    },
    {
      image: SalmonRoll.src,
      title: "Salmon Roll",
      label: "Salmon",
      raiting: 3,
      backgroundColor: "secondary.blush.300",
    },
    {
      image: CupCake.src,
      title: "Cupcake Choco",
      label: "Cupcake",
      raiting: 4,
      backgroundColor: "primary.300",
    },
    {
      image: DoughnutMilk.src,
      title: "Doughnut Milk",
      label: "Doughnut",
      raiting: 5,
      backgroundColor: "secondary.sushi.300",
    },
    {
      image: DoughnutUnicorn.src,
      title: "Doughnut Unicorn",
      label: "Doughnut",
      raiting: 4,
      backgroundColor: "secondary.sushi.300",
    },
    {
      image: KathiKebab.src,
      title: "Kathi Kebab",
      label: "Kebab",
      raiting: 4,
      backgroundColor: "secondary.sanMarino.300",
    },
  ];

  return {
    props: {
      category,
      trending,
    },
  };
};
